apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: golang-app.example.com.20240119170446.0.0
spec:
  refName: golang-app.example.com
  version: 20240119170446.0.0
  releaseNotes: |
    Release v20240119170446.0.0 of package golang-app.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd7e0e0c8fe56302918c2d7a69.azurecr.io/tap-install/tcc-test/golang-app683326-bundle@sha256:c5eb16248e17b650f7bdfada1a2c3d80d00dc6227d7cd94bffe1a19e32714474
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
