apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: maven-app.example.com.20240119170445.0.0
spec:
  refName: maven-app.example.com
  version: 20240119170445.0.0
  releaseNotes: |
    Release v20240119170445.0.0 of package maven-app.example.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd7e0e0c8fe56302918c2d7a69.azurecr.io/tap-install/tcc-test/maven-app683326-bundle@sha256:70dff1536e3ec267eb5c3d9f057c8994245209d3d1aa836b05c6ea1e9b5fdb20
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
